import { useMemo, useState } from "react";
import { ArrowLeft, Star, Volume2 } from "lucide-react";
import { tenLevelTerms } from "@/data/tenLevelCatalog";
import { clearTenLevelReview, readTenLevelReview, writeTenLevelReview } from "@/lib/tenLevelReview";
import { getLanguageWord, getLanguageWordCounterpart } from "@/lib/wordLanguageVariants";
import { useChineseScript } from "@/contexts/ChineseScriptContext";

export function TenLevelReview({ familyUnlocked, onRequestUnlock, onBack, onPlay }: { familyUnlocked: boolean; onRequestUnlock: () => void; onBack: () => void; onPlay: (term: string, language: "cantonese" | "mandarin") => void }) {
  const { displayText } = useChineseScript();
  const [saved, setSaved] = useState(() => readTenLevelReview());
  const [confirmClear, setConfirmClear] = useState(false);
  const terms = useMemo(() => saved.map(term => tenLevelTerms.find(item => item.term === term)).filter((item): item is typeof tenLevelTerms[number] => Boolean(item)).filter(item => familyUnlocked || item.level === 1), [familyUnlocked, saved]);
  const remove = (term: string) => setSaved(values => { const next = values.filter(value => value !== term); writeTenLevelReview(next); return next; });
  const clearAll = () => { clearTenLevelReview(); setSaved([]); setConfirmClear(false); };
  return <div className="mx-auto min-h-screen max-w-md bg-[#FFF9ED] px-4 pb-8 pt-4 text-[#26324B]"><header className="flex items-center justify-between"><button onClick={onBack} className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-[#47745D] shadow-sm" aria-label="返回"><ArrowLeft className="h-5 w-5" /></button><div className="text-center"><p className="font-serif text-2xl font-black">溫習庫</p><p className="mt-0.5 text-xs font-bold text-[#76839A]">已收藏 {terms.length} 個詞語</p></div><div className="w-11" /></header>{!familyUnlocked && <button onClick={onRequestUnlock} className="mt-4 w-full rounded-2xl border-2 border-[#F2DEAB] bg-[#FFF8E7] px-4 py-3 text-sm font-black text-[#8A7040]">第 2 至第 10 級收藏詞需要家長家庭完整解鎖</button>}{terms.length === 0 ? <section className="mt-10 rounded-[2rem] bg-white px-7 py-12 text-center shadow-sm"><Star className="mx-auto h-12 w-12 text-[#F5C34E]" /><h1 className="mt-4 text-xl font-black">還沒有收藏詞語</h1><p className="mt-2 font-bold leading-6 text-[#718095]">在練習頁按下星星，就可以把想重溫的詞語放到這裡。</p></section> : <><section className="mt-4 rounded-2xl border-2 border-[#F4D9D3] bg-[#FFF8F5] p-3 text-center"><p className="text-xs font-bold leading-5 text-[#A76B64]">已學會的字詞可逐張按右上角星星取消收藏；亦可一次清空。</p>{confirmClear ? <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => setConfirmClear(false)} className="rounded-xl bg-white px-3 py-2.5 text-sm font-black text-[#68798E] shadow-sm">保留字詞</button><button onClick={clearAll} className="rounded-xl bg-[#E97D76] px-3 py-2.5 text-sm font-black text-white shadow-[0_3px_0_#C85F5A] active:translate-y-0.5 active:shadow-none">確定清空</button></div> : <button onClick={() => setConfirmClear(true)} className="mt-3 rounded-xl border-2 border-[#F0C4BD] bg-white px-4 py-2 text-sm font-black text-[#B85E5A] transition active:scale-95">一鍵清空溫習庫</button>}</section><div className="mt-4 grid gap-3">{terms.map(item => { const primary = displayText(getLanguageWord(item.term, "cantonese")); const counterpart = getLanguageWordCounterpart(item.term, "cantonese"); return <article key={item.term} className="rounded-[1.5rem] bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><strong className="text-2xl text-[#40526D]">{primary}</strong>{counterpart && <p className="mt-0.5 font-serif text-base font-black text-[#76839A]">（{displayText(counterpart)}）</p>}</div><button onClick={() => remove(item.term)} className="grid h-10 w-10 place-items-center rounded-full bg-[#FFF1E8] text-[#E27972]" aria-label={`取消收藏 ${displayText(item.term)}`}><Star className="h-5 w-5" fill="currentColor" /></button></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => onPlay(item.term, "cantonese")} className="voice-button voice-canto"><Volume2 className="h-4 w-4" />粵語</button><button onClick={() => onPlay(item.term, "mandarin")} className="voice-button voice-mandarin"><Volume2 className="h-4 w-4" />普通話</button></div></article>; })}</div></>}</div>;
}
